### ISSUE TITLE
When run according to README.md, it shows that the key file was not found.

### ISSUE THREAD

**Issue by PengLiao12** [CownowAn/DiffusionNAG#1]
For example:
###  Transfer NAG
> FileNotFoundError: [Errno 2] No such file or directory: './configs/transfer_nag_config.pt'
### Trasin score network 
> FileNotFoundError: [Errno 2] No such file or directory: './data/transfer_nag/nasbench201_info.pt'
### Train meta-predictor
> FileNotFoundError: [Errno 2] No such file or directory: './data/transfer_nag/meta_train_tasks_predictor.pt'

Then I tried to get the file with the same name from MetaD2A:

> self.igraph_list = data['g']
KeyError: 'g'

This is a great research work that captured my interest. I would be grateful if you could provide or hints on how to generate these key files.

**Comment by CownowAn** [comment]
Thank you for your interest in our work and I'm sorry for any inconvenience caused. I've added the file to address this issue. Feel free to let us know if you encounter any problems. Thanks!

**Comment by PengLiao12** [comment]
Thank you for replying so quickly. I have updated the files.
