### ISSUE TITLE
About Novelty Evaluation for NAS-Bench-201

### ISSUE THREAD

**Issue by mufeili** [CownowAn/DiffusionNAG#2]
Thank you for sharing this great codebase! 

I'm interested in reproducing the results for NAS-Bench-201 in the table 4 of your paper (https://arxiv.org/pdf/2305.16943.pdf). It seems that the instruction listed in the README file `bash script/tr_scorenet.sh` trains a model on the entire dataset rather than a subset of 7,812 architectures, resulting in a novelty score of 0 during the evaluation. Have you recorded the chosen 7,812 architectures anywhere? Do you have any other suggestions for reproducing this result? Thank you.

**Comment by CownowAn** [comment]
Thank you for your interest in our work! I suggest setting `data.split_ratio = 0.5` in `NAS-Bench-201/configs/tr_scorenet.py`. Feel free to let us know if you encounter any problems. Thanks!

**Comment by mufeili** [comment]
Thank you so much for the quick response! It works.
