### ISSUE TITLE
About Graph Structure Generation

### ISSUE THREAD

**Issue by mufeili** [CownowAn/DiffusionNAG#3]
Thanks again for sharing the amazing codebase and I've learnt a lot from it!

From the implementation [here](https://github.com/CownowAn/DiffusionNAG/blob/main/NAS-Bench-201/losses.py#L127), it seems that DiffusionNAG just treats the DAG as fixed conditional information, and only corrupts and generates node features (operator types). Have you tried using DiffusionNAG for DAG structure generation? I think DiffusionNAG extends GDSS, which is capable of generating graph structures. Thanks.

**Comment by CownowAn** [comment]
Good to hear that you've learned a lot! 

We evaluated DiffusionNAG on two search spaces with fixed adjacency, so you understand correctly. I think you can think of it as similar to the continuous version of EDP-GNN.
Although GDSS generates both nodes and adjacency jointly, we observed that it fails when we attempt to apply it to our scenario. If you'd like to discuss more about research in this direction, feel free to contact me at `sohyunan@kaist.ac.kr`. :)

**Comment by mufeili** [comment]
Got it. Thanks!
